on: [pull_request]

jobs:
  getdata:
    runs-on: ubuntu-latest
    name: Get code context with Watermelon
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Watermelon-context-action
        uses: watermelontools/watermelon-context-action@v1.0
